name:                exnihilo
version:             0.1.0.0
github:              "t4ccer/exnihilo"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccre@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/t4ccer/exnihilo#readme>

dependencies:
- base >= 4.10.0 && < 5
- optparse-applicative
- containers
- unordered-containers
- transformers
- mtl
- text
- bytestring
- data-default
- can-i-haz
- directory
- filepath
- yaml
- aeson

library:
  source-dirs: src

executables:
  exnihilo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-do-bind
    - -Wpartial-fields
    - -Wincomplete-uni-patterns
    dependencies:
    - exnihilo

